apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress-deployment
  name: wordpress-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      kubernetes.io/app: wordpress-deployment
  template:
    metadata:
      labels:
        kubernetes.io/app: wordpress-deployment
    spec:
      containers:
      - image: wordpress:php8.2
        name: wordpress
        ports:
          - containerPort: 80
            name: wordpress-http
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: wordpress-http
        #   initialDelaySeconds: 3
        #   periodSeconds: 3
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb-svc.default.svc.cluster.local
        # value: mariadb-svc
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mariadb-cm
              key: MARIADB_DATABASE
              optional: false
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              name: mariadb-cm
              key: mariadb_user
              optional: false
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: mariadb_user_password
              optional: false
