---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mariadb-sts
  name: mariadb-sts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-sts
  serviceName: mariadb-svc
  template:
    metadata:
      labels:
        app: mariadb-sts
    spec:
      containers:
      - image: mariadb:10.7.7
        name: mariadb
        ports:
        - containerPort: 3306
          name: mariadb-port
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: MARIADB_ROOT_PASSWORD
              optional: false
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: mariadb_user_password
              optional: false
        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mariadb-cm
              key: MARIADB_DATABASE
              optional: false
        - name: MARIADB_USER
          valueFrom:
            configMapKeyRef:
              name: mariadb-cm
              key: mariadb_user
              optional: false




